# Namespace: minio-dev
apiVersion: v1
kind: Namespace
metadata:
  name: minio-dev
---
# MinIO Deployment
# Using default credentials for simplicity
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          env:
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          command:
          - /bin/bash
          - -c
          args:
          - minio server /data --console-address :9090
          ports:
            - containerPort: 9000
            - containerPort: 9090
          volumeMounts:
            - mountPath: /data
              name: localvolume
      volumes:
        - name: localvolume
          hostPath:
            path: /tmp/minio/data
            type: DirectoryOrCreate
---
# MinIO Service
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-dev
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: webui
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
# Job to create a bucket in MinIO
# The bucket is created with the name "artifacts" and the policy is set to public
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
  namespace: minio-dev
spec:
  template:
    spec:
      containers:
        - name: create-bucket
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
            - |
              mc alias set myminio http://minio-service.minio-dev.svc.cluster.local:9000 minioadmin minioadmin && \
              mc mb pipe-manager/artifacts && \
              mc policy set public pipe-manager/artifacts
      restartPolicy: OnFailure
---
# Secret to store the S3 credentials for the artifacts bucket in Pipe-Manger
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: pipe-manager
type: Opaque
data:
  aws_access_key_id: bWluaW9hZG1pbg==
  aws_secret_access_key: bWluaW9hZG1pbg==